plugins:
  - jekyll-relative-links
relative_links:
  enabled: false
  collections: false
include:
  - README.md
  -html/guidemaker/index.html

#theme: jekyll-theme-hacker
remote_theme: rundocs/jekyll-rtd-theme
