plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - html/guidemaker/index.html

#theme: jekyll-theme-hacker
remote_theme: rundocs/jekyll-rtd-theme
