title: GuideMaker
description: Software to design gRNAs pools in non-model genomes and CRISPR-Cas systems.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author:  USDA-ARS-GBRU
repo_url: 'https://github.com/USDA-ARS-GBRU/GuideMaker'
edit_on_github: false
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
