title: GuideMaker
description: Software to design gRNAs pools in non-model genomes and CRISPR-Cas systems.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: USDA-ARS-GBRU
repo_url: "https://github.com/USDA-ARS-GBRU/GuideMaker"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
