name: Codecov

on: [pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.MY_CODECOV_TOKEN }} # not required for public repos
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
