name: Publish Docker image
on:
  push:
    branches: main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.MY_GITHUB_RESISTRY_TOKEN }}

    - name: Build container image and push
      uses: docker/build-push-action@v2
      with:
        context: docker-images/avx
        push: true
        tags: ghcr.io/usda-ars-gbru/guidemaker-avx:latest-sha-${{ steps.slug.outputs.sha8 }}
