name: Build Tests Docker-Images API-Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest # can be run on other OS as well.
    strategy:
      matrix:
        python-version: [3.7] # other version of python can be pass as a list

    steps:
    - uses: actions/checkout@v2 # Get a copy of code from github
    - name: Set up Python ${{ matrix.python-version }} # set up python from github
      uses: actions/setup-python@v2 
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2 # https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
    - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip
        # Install build deps
        python -m pip install setuptools wheel twine versioneer
        pip install --no-binary :all: nmslib
        pip install -r requirements.txt
        # Install the package from setup.py
        python setup.py install